Add boostrap layout
front-end-by-rimantas/34-grupe-portfolio-docland pull request #30
Opened 2022-01-29 13:26 UTC by Lasmorfijus1

2022-01-30 08:00 UTC, belauzas requested changes

2022-01-30 08:00 UTC, belauzas commented on css/bootstrap/bootstrap-grid.css
> +}
Šito nereikia

2022-02-03 10:40 UTC, belauzas commented
Tai kad dar nepataisyta pagal mano prieš tai minėtą pastabą ;)

2022-02-06 09:48 UTC, Rokelis3 approved these changes

2022-02-06 10:39 UTC, Rokelis3 approved these changes

2022-02-07 18:09 UTC, belauzas approved these changes

2022-02-07 18:10 UTC, merged