Fonts colors and sizes
front-end-by-rimantas/34-grupe-portfolio-docland pull request #32
Opened 2022-01-30 16:22 UTC by Rokelis3

Sudėtos visos spalvos, pagrindiniai headerių dydžiai ir visa info reikalinga fontams. Viską naudokit per :root. Kaip kas užvadinta matysit: css/base/base.css.

2022-01-30 16:50 UTC, AFEDev requested changes
Bootstrap bibliotekos buvom sutare nanaudoti?

2022-02-01 13:08 UTC, AFEDev approved these changes

2022-02-01 13:08 UTC, AFEDev approved these changes

2022-02-01 18:19 UTC, AFEDev approved these changes

2022-02-01 18:37 UTC, Lasmorfijus1 approved these changes

2022-02-01 18:37 UTC, merged